export type Deck = { title:string; slug:string; slides:number; type:string; tags:string[]; lang:string; desc:string; color:string; date:string };
export type DeckSlide = {
  layout: 'cover'|'bullets'|'code'|'cards'|'split';
  subtitle: string; title: string; message?: string;
  points?: string[]; code?: string; cards?: {title:string;desc:string;icon:string}[];
  leftTitle?: string; leftPoints?: string[]; rightTitle?: string; rightPoints?: string[];
  gradient?: string;
};
export type Post = { title:string; slug:string; tag:string; date:string; desc:string; color:string; accent:string };
export type PostSlide = { num:string; label:string; title:string; body:string; theme:'white'|'black'; bullets?:string[]; code?:string|null };
export type BlogPost = { title:string; slug:string; date:string; mins:number; tags:string[]; excerpt:string; featured?:boolean };

export const decksData: Deck[] = [
  {title:"Cut Your Claude Bill By 90%", slug:"save-claude-tokens-rtk-caveman", slides:9, type:"Editorial Deck", tags:["claude-code","ai"], lang:"EN", desc:"A short editorial deck on saving Claude tokens with two small tools. RTK trims noisy bash output before it reaches the model; Caveman compresses Claude's replies.", color:"from-violet-600/30 to-fuchsia-500/20", date:"2026-05-18"},
  {title:"Cron Jobs, Explained", slug:"cron-jobs-101", slides:9, type:"Editorial Deck", tags:["devops","automation"], lang:"EN", desc:"A short editorial deck on cron jobs for engineers who haven't written one yet. Covers the mental model, the syntax, three real examples, and the wrappers.", color:"from-amber-500/25 to-orange-500/20", date:"2026-05-15"},
  {title:"Container Queries & The Em Cascade", slug:"css-container-queries", slides:9, type:"Editorial Deck", tags:["css","frontend"], lang:"EN", desc:"A short editorial deck on the CSS pattern that makes components scale uniformly, the way an image being resized does, using container queries, cqi units, and an em cascade.", color:"from-emerald-600/25 to-teal-500/20", date:"2026-05-15"},
  {title:"Rubik’s Cube 101", slug:"rubiks-cube-101", slides:18, type:"Presentation Deck", tags:["hobby","education"], lang:"EN", desc:"A beginner-friendly presentation about cube history, notation, solving basics, and the broader speedcubing hobby.", color:"from-sky-500/25 to-blue-600/20", date:"2026-05-12"},
  {title:"Mobile Development Frameworks in 2026", slug:"mobile-frameworks", slides:20, type:"Editorial Deck", tags:["mobile","react-native"], lang:"EN / ID", desc:"A strategic overview of React Native, Flutter, Kotlin Multiplatform, Native, and hybrid approaches for modern mobile teams.", color:"from-zinc-700/40 to-zinc-900", date:"2026-05-10"},
  {title:"AI Coding Agent", slug:"ai-coding-agent", slides:9, type:"Spotlight Deck", tags:["ai","developer-tools"], lang:"EN", desc:"An executive deck on how AI coding agents actually work: when to use them, how to prompt them, and what guardrails keep speed from turning into chaos.", color:"from-purple-600/25 to-indigo-600/20", date:"2026-05-08"},
];

export const deckSlides: Record<string, DeckSlide[]> = {
  "cron-jobs-101":[
    {layout:"cover", subtitle:"Five Asterisks And A Command", title:"Cron Jobs, Explained", message:"If you keep running scripts manually, you are the cron job. This deck fixes that in nine slides.", points:["Designed for engineers who haven't written one yet.","Same syntax that has run servers for forty years, dressed up by every modern platform."], gradient:"from-amber-500/20 via-transparent to-orange-500/15"},
    {layout:"bullets", subtitle:"If You Do It Twice, Automate It", title:"You Are Already The Cron Job", message:"Every team has the script someone runs by hand. Eventually that someone gets sick, or distracted, or quits.", points:["The daily backup that runs only when you remember.","The weekly report you email at 9am Monday because the boss expects it.","The cache cleanup that breaks production when you skip a week.","The deploy script you run twice before realising it ran the first time."], gradient:"from-zinc-800 to-zinc-900"},
    {layout:"code", subtitle:"The Whole Mental Model", title:"It's Just Schedule Plus Command", message:"A cron job is a single line. Five fields that say when, followed by what to run.", code:"# Format\n<minute> <hour> <day-of-month> <month> <day-of-week>  <command>\n\n# Run every day at 06:00\n0 6 * * *  /usr/local/bin/backup.sh\n\n# Run every Monday at 09:00\n0 9 * * 1  npm run weekly-report", points:["Five fields. One command.","The asterisks just mean 'any value'."]},
    {layout:"code", subtitle:"Minute, Hour, Day, Month, Weekday", title:"Read It Left To Right", message:"Each column has its own range. Use a number for exact, a comma for list, a slash for interval.", code:"*  *  *  *  *  command\n|  |  |  |  |\n|  |  |  +----- day of week (0-6)\n|  |  +-------- month (1-12)\n|  +----------- day of month (1-31)\n+-------------- minute (0-59)\n\n*/15 * * * *   every 15 minutes\n0 9 * * 1-5    weekdays at 09:00", points:["Numbers for exact, slash for stride."]},
    {layout:"code", subtitle:"Copy, Tweak, Ship", title:"Three Lines You'll Actually Write", message:"Most cron jobs are one of these three shapes.", code:"# Daily housekeeping at 03:00\n0 3 * * *  /var/scripts/rotate-logs.sh\n\n# Every five minutes weekdays\n*/5 9-17 * * 1-5  curl -fsS https://api.internal/health\n\n# First day of month at 09:00\n0 9 1 * *  node scripts/send-invoices.js", points:["Use crontab.guru to verify before deploying.","Comment every job."]},
    {layout:"cards", subtitle:"Same Idea, Friendlier Wrappers", title:"Where Cron Lives Today", message:"You don't need to SSH into a VPS anymore.", cards:[{title:"Linux crontab",desc:"The classic. crontab -e on any Unix box.",icon:"◰"},{title:"Vercel Cron",desc:"A crons block in vercel.json pointing at a route.",icon:"⚡"},{title:"GitHub Actions",desc:"Workflow with a schedule trigger. Great for repo maintenance.",icon:"‹›"},{title:"App-level libs",desc:"node-cron, BullMQ, APScheduler inside your process.",icon:"⬢"}]},
    {layout:"bullets", subtitle:"Trip On These Once, Never Again", title:"The Two Things That Bite", message:"Every engineer has a story about a cron job that ran late or never.", points:["Timezone. Most cron defaults to UTC — 0 9 * * * runs at 4pm WIB.","No retries. Log everything and alert on failure.","Concurrency. Add a lock if job may overlap.","Silent success. Pipe output to a log."], gradient:"from-amber-900/20 to-zinc-900"},
    {layout:"split", subtitle:"The Job I Avoided For Five Years", title:"A Tiny Personal Story", leftTitle:"Before", leftPoints:["Every morning I ran a script by hand.","Assumed cron required special permissions.","Five asterisks looked like regex."], rightTitle:"After", rightPoints:["One Friday I typed crontab -e.","Five minutes of reading. Syntax fit on a napkin.","The next morning it ran without me."], gradient:"from-amber-500/10 to-zinc-900"},
    {layout:"bullets", subtitle:"Three Lines To Remember", title:"Takeaways", message:"The scary syntax was a tax you were paying by not learning it.", points:["Anything you do twice on a schedule belongs in cron.","Five fields, one command — fits on a sticky note.","Pick the wrapper that matches your stack."], gradient:"from-amber-500/15 via-transparent to-orange-500/10"},
  ],
  "save-claude-tokens-rtk-caveman":[
    {layout:"cover", subtitle:"Two Tiny Tools, One Habit", title:"Cut Your Claude Bill By 90%", message:"Tokens drain in two places: bash output piped back, and the model's own verbose replies.", points:["RTK filters noisy bash before it reaches the model.","Caveman compresses Claude's prose by ~75%."], gradient:"from-violet-600/30 to-fuchsia-600/20"},
    {layout:"bullets", subtitle:"Where The Bill Comes From", title:"Every Tool Call Costs", message:"A typical Claude Code session runs 80+ tool calls.", points:["git status → 40 lines, only 3 matter.","grep → 200 hits, model reads all.","Polite prose → 300 tokens of hedging."], gradient:"from-zinc-800 to-zinc-900"},
    {layout:"code", subtitle:"The First Filter", title:"RTK — Rust Token Killer", message:"A tiny CLI proxy that sits between bash and the model.", code:"# Install\ncargo install rtk\n\n# Wrap any command\nrtk -- git status\nrtk -- grep -r \"TODO\" src/\n\n# Output before: 1800 tokens\n# Output after: 180 tokens", points:["Trims output before it counts.","10 minutes setup, 90% off forever."]},
    {layout:"code", subtitle:"The Second Filter", title:"Caveman Mode", message:"A communication skill that rewrites Claude's replies into terse bullets.", code:"// Before: 250 tokens\n\"I'd be happy to help! Let me explain...\"\n\n// After: 45 tokens\n\"- Fixed auth bug at src/auth.ts:42\n- Added retry with backoff\n- Test: npm test -- auth\"", points:["Cuts reply tokens ~75%.","Keeps signal, drops ceremony."]},
    {layout:"cards", subtitle:"The Habit That Ties It", title:"Stop Narrating Tools", message:"Don't let Claude describe every tool call.", cards:[{title:"RTK",desc:"Filters bash noise before model.",icon:"◰"},{title:"Caveman",desc:"Compresses prose after model.",icon:"✦"},{title:"Habit",desc:"Answer, don't narrate.",icon:"↻"},{title:"Result",desc:"90% cheaper, faster sessions.",icon:"✓"}]},
    {layout:"bullets", subtitle:"What You Keep", title:"Signal Over Ceremony", message:"You still get full reasoning — just without filler.", points:["Fix location with file:line","Why it broke","Exact edit to apply"], gradient:"from-violet-900/20 to-zinc-900"},
    {layout:"split", subtitle:"Before / After Bill", title:"One Session, Two Bills", leftTitle:"Before RTK+Caveman", leftPoints:["Avg session 120k tokens","~$1.80 per session","20 sessions → $36"], rightTitle:"After", rightPoints:["Avg session 12k tokens","~$0.18 per session","20 sessions → $3.60"], gradient:"from-violet-600/20 to-zinc-900"},
    {layout:"bullets", subtitle:"Setup In Ten Minutes", title:"Try It Today", message:"Add two tools, change one prompt.", points:["Install RTK, prefix bash calls.","Add Caveman as a skill.","Tell Claude: 'Be brief. No preamble.'"], gradient:"from-fuchsia-600/20 to-zinc-900"},
    {layout:"bullets", subtitle:"Keep The Savings", title:"Takeaways", message:"Small proxies compound fast.", points:["Filter before the model, compress after.","Cost is a design choice.","Your next session can be 90% cheaper."], gradient:"from-violet-500/20 to-zinc-900"},
  ]
};

export const postsData: Post[] = [
  {title:"Stop Burning Claude Credits", slug:"save-claude-tokens-rtk-caveman", tag:"tips", date:"2026-05-18", desc:"Every git status, every grep, every paragraph of polite prose costs tokens. Two tools cut a normal session's bill by 90%. Setup takes ten minutes.", color:"bg-white text-black", accent:"tips"},
  {title:"Stop Running Things Manually", slug:"cron-jobs-in-five-minutes", tag:"tips", date:"2026-05-18", desc:"If you keep opening the terminal to run the same command on the same schedule, you are the cron job. It's time to fix that.", color:"bg-zinc-900 text-white border border-zinc-800", accent:"tips"},
  {title:"Components That Scale", slug:"css-container-queries", tag:"css", date:"2026-05-15", desc:"Stop using media queries when you need a component to look right in a sidebar AND a hero. There's a one-line fix.", color:"bg-white text-black", accent:"css"},
  {title:"Your AI Is Not Autocomplete", slug:"ai-coding-agent-operating-model", tag:"coding", date:"2026-05-14", desc:"It's a fast junior who needs direction. Get it right and you ship faster. Get it wrong and you ship confident garbage.", color:"bg-zinc-900 text-white border border-zinc-800", accent:"coding"},
  {title:"Pick Your Mobile Stack", slug:"mobile-frameworks-2026", tag:"tips", date:"2026-05-10", desc:"There's no universal winner. Only a winner for your team, your timeline, and the product you're actually building.", color:"bg-white text-black", accent:"tips"},
  {title:"You Can Solve The Cube", slug:"rubiks-cube-beginner-flow", tag:"hobby", date:"2026-05-08", desc:"Not in 20 seconds. But in a weekend. The trick is to stop trusting your instincts and start trusting layers.", color:"bg-zinc-900 text-white border border-zinc-800", accent:"hobby"},
];

export const postsSlides: Record<string, PostSlide[]> = {
  "cron-jobs-in-five-minutes":[
    {num:"", label:"tips", title:"Stop Running Things Manually", body:"If you keep opening the terminal to run the same command on the same schedule, you are the cron job. It's time to fix that.", theme:"black", code:null, bullets:null} as any,
    {num:"02", label:"The Pain", title:"You Are Already The Cron Job", body:"Every morning. Every Friday. Every deploy. You SSH in, run the thing, close the window. Until you forget once, and now there's an incident.", bullets:["Daily backup you keep meaning to script.","Cleanup that fails when you go on holiday.","Manual reports that should email themselves."], theme:"black"} as any,
    {num:"03", label:"The Idea", title:"It's Just A Schedule + Command", body:"A cron job is one line. Five fields that say when, followed by the command.", code:"# Run every day at 6am\n0 6 * * *  /usr/local/bin/backup.sh\n\n# Run every Monday at 9am\n0 9 * * 1  npm run weekly-report", theme:"black"} as any,
    {num:"04", label:"The Syntax", title:"Five Asterisks, Read Left To Right", body:"Minute, hour, day-of-month, month, day-of-week. Use a number, a list, or a star for any.", code:"*  *  *  *  *  command", theme:"black"} as any,
    {num:"05", label:"Where It Lives", title:"Pick The Wrapper That Fits", body:"The five asterisks haven't changed in decades.", bullets:["Linux: crontab -e","Vercel: vercel.json","GitHub Actions","App-level libs"], theme:"black"} as any,
    {num:"06", label:"Gotchas", title:"Two Things That Will Bite", body:"Almost everyone trips on the same two issues.", bullets:["Timezone: UTC by default.","No retries: log everything."], theme:"black"} as any,
    {num:"07", label:"Closing", title:"Five Asterisks. That's The Whole Wall.", body:"The syntax looked scary, so you ran things by hand.", bullets:["If you do it twice, automate it."], theme:"black"} as any,
  ],
  "save-claude-tokens-rtk-caveman":[
    {num:"", label:"tips", title:"Stop Burning Claude Credits", body:"Every git status costs tokens.", theme:"white"} as any,
    {num:"02", label:"Where Tokens Go", title:"It's Not The Code", body:"Bash output and verbose replies.", bullets:["git status 200 lines","Great question!"], theme:"white"} as any,
    {num:"03", label:"Tool 1", title:"RTK Filters Bash Before It Speaks", body:"Rust Token Killer proxy.", code:"brew install rtk", theme:"white"} as any,
    {num:"04", label:"Tool 2", title:"Caveman Compresses Replies", body:"Drop filler, keep signal.", code:"/caveman", theme:"white"} as any,
    {num:"05", label:"Combined", title:"Roughly 90% Off", body:"Together 200k → 25k.", bullets:["RTK 60-90%","Caveman 75%"], theme:"white"} as any,
    {num:"06", label:"Gotchas", title:"Two Things To Know", body:"Opinionated but fixable.", bullets:["find syntax","blunt"], theme:"white"} as any,
    {num:"07", label:"Closing", title:"Ten Minutes, Months Of Credits", body:"Install both tonight.", theme:"white"} as any,
  ]
};

export const blogData: BlogPost[] = [
  {title:"From four repos to a monorepo", slug:"four-repos-to-a-monorepo", date:"2026-06-21", mins:3, tags:["monorepo","Expo","Metro","refactor","architecture"], excerpt:"Consolidating four byte-identical app repos into one shared core plus thin app shells, the expo-router and Metro problems it surfaced, and validating the migration with real bundles.", featured:true},
  {title:"Shipping, then listening", slug:"shipping-then-listening", date:"2026-06-20", mins:3, tags:["UX","feedback","mobile","indie"], excerpt:"The first round of real tester feedback and the small, high-leverage fixes it produced: grid spacing, free typing, jump buttons, easing early ads, and a well-timed review prompt."},
  {title:"The Play Store gauntlet", slug:"the-play-store-gauntlet", date:"2026-06-19", mins:3, tags:["Google Play","launch","mobile","indie"], excerpt:"Everything between a finished app and a live listing: store assets, data safety, content rating, the target-audience trap, app-ads.txt, and the testing tracks."},
  {title:"A cross-app discount with no backend", slug:"cross-app-discount-no-backend", date:"2026-06-18", mins:3, tags:["architecture","RevenueCat","deep linking","mobile"], excerpt:"Giving players 50% off in a sibling app when they already paid in one, using a deep-link handshake instead of sign-in."},
  {title:"Mobile in-app purchases: what nobody warns you about", slug:"mobile-iap-what-nobody-warns-you-about", date:"2026-06-17", mins:3, tags:["RevenueCat","AdMob","Google Play","monetization","mobile"], excerpt:"AdMob, RevenueCat, and Google Play Billing in practice. Products versus entitlements versus offerings, the 'purchase unavailable' debugging."},
  {title:"A hint economy that's fair but not free", slug:"a-fair-hint-economy", date:"2026-06-16", mins:3, tags:["game design","monetization","React Native"], excerpt:"Designing hints that monetize without feeling hostile: a regenerating free tier, never-expiring bonus hints, streak rewards."},
  {title:"Building a crossword engine in React Native", slug:"building-a-crossword-engine-react-native", date:"2026-06-15", mins:3, tags:["React Native","Expo","gestures","game dev"], excerpt:"Exact-hit-test tappable cells, pinch-zoom with breathing room, an interlocking offline level generator."},
  {title:"One idea, four apps", slug:"one-idea-four-apps", date:"2026-06-14", mins:3, tags:["product","architecture","Expo","mobile"], excerpt:"The product and architecture bet behind shipping a family of four themed crossword games from a single shared codebase."},
  {title:"Building four apps with an AI coding agent", slug:"building-four-apps-with-an-ai-agent", date:"2026-06-13", mins:3, tags:["AI coding agent","React Native","Expo","indie","mobile"], excerpt:"How I shipped a family of four crossword games to the Play Store by pairing with an AI coding agent."},
  {title:"How I cut my Claude token bill by 90%", slug:"how-i-cut-claude-tokens-90-percent", date:"2026-05-18", mins:6, tags:["claude-code","ai","productivity"], excerpt:"Two tiny tools and one habit. RTK trims bash output before it reaches the model. Caveman trims the model's replies."},
  {title:"The cron job I avoided for five years", slug:"the-cron-job-i-avoided-for-five-years", date:"2026-05-16", mins:5, tags:["devops","automation"], excerpt:"I ran the same script by hand for years because cron looked like a foreign language. It took five minutes to learn."},
  {title:"Components that scale like images", slug:"components-that-scale-like-images", date:"2026-05-15", mins:4, tags:["css","frontend"], excerpt:"A small CSS pattern that turned out to be the missing piece: container queries plus an em cascade."},
];

export const blogFull: Record<string, {lead:string; sections:{id:string; title:string; body:string}[]}> = {
  "the-play-store-gauntlet": { lead:"The code was done. Then I met the Play Console. Here is the checklist I assembled the hard way, four times.", sections:[
    {id:"store-listing-assets", title:"Store listing assets", body:`<ul class="list-disc pl-5 space-y-1.5 text-zinc-300"><li>Icon 512, Feature graphic 1024×500, screenshots</li><li>Generated with Pillow gradient</li></ul>`},
    {id:"data-safety-honestly", title:"Data safety, honestly", body:`<p>The Data safety form asks what data you collect. AdMob, Sentry, RevenueCat.</p>`},
    {id:"the-target-audience-trap", title:"The target-audience trap", body:`<p>Ticking under-13 opts into Families policy.</p>`},
  ]}
};
