export type Deck = { title:string; slug:string; slides:number; type:string; tags:string[]; lang:string; desc:string; color:string; date:string };
export type DeckSlide = {
  layout: 'cover'|'bullets'|'code'|'cards'|'split';
  subtitle: string; title: string; message?: string;
  points?: string[]; code?: string; cards?: {title:string;desc:string;icon:string}[];
  leftTitle?: string; leftPoints?: string[]; rightTitle?: string; rightPoints?: string[];
  gradient?: string;
};
export type Post = { title:string; slug:string; tag:string; date:string; desc:string; color:string; accent:string };
export type PostSlide = { num:string; label:string; title:string; subtitle?:string; body:string; theme:'white'|'black'; bullets?:string[]; code?:string|null };
export type BlogPost = { title:string; slug:string; date:string; mins:number; tags:string[]; excerpt:string; featured?:boolean };
export type Video = { id:string; title:string; desc:string; thumb:string; date:string; duration:string; views:string; isShort:boolean; tag:string };

export const decksData: Deck[] = [
  {title:"Cut Your Claude Bill By 90%", slug:"save-claude-tokens-rtk-caveman", slides:9, type:"Editorial Deck", tags:["claude-code","ai"], lang:"EN", desc:"A short editorial deck on saving Claude tokens with two small tools. RTK trims noisy bash output before it reaches the model; Caveman compresses Claude's replies.", color:"from-violet-600/30 to-fuchsia-500/20", date:"2026-05-18"},
  {title:"Cron Jobs, Explained", slug:"cron-jobs-101", slides:9, type:"Editorial Deck", tags:["devops","automation"], lang:"EN", desc:"A short editorial deck on cron jobs for engineers who haven't written one yet. Covers the mental model, the syntax, three real examples, and the wrappers.", color:"from-amber-500/25 to-orange-500/20", date:"2026-05-15"},
  {title:"Container Queries & The Em Cascade", slug:"css-container-queries", slides:9, type:"Editorial Deck", tags:["css","frontend"], lang:"EN", desc:"A short editorial deck on the CSS pattern that makes components scale uniformly, the way an image being resized does, using container queries, cqi units, and an em cascade.", color:"from-emerald-600/25 to-teal-500/20", date:"2026-05-15"},
  {title:"Rubik’s Cube 101", slug:"rubiks-cube-101", slides:18, type:"Presentation Deck", tags:["hobby","education"], lang:"EN", desc:"A beginner-friendly presentation about cube history, notation, solving basics, and the broader speedcubing hobby.", color:"from-sky-500/25 to-blue-600/20", date:"2026-05-12"},
  {title:"Mobile Development Frameworks in 2026", slug:"mobile-frameworks", slides:20, type:"Editorial Deck", tags:["mobile","react-native"], lang:"EN / ID", desc:"A strategic overview of React Native, Flutter, Kotlin Multiplatform, Native, and hybrid approaches for modern mobile teams.", color:"from-zinc-700/40 to-zinc-900", date:"2026-05-10"},
  {title:"AI Coding Agent", slug:"ai-coding-agent", slides:9, type:"Spotlight Deck", tags:["ai","developer-tools"], lang:"EN", desc:"An executive deck on how AI coding agents actually work: when to use them, how to prompt them, and what guardrails keep speed from turning into chaos.", color:"from-purple-600/25 to-indigo-600/20", date:"2026-05-08"},
  {title:"Kotlin Multiplatform: Leverage, Not Replacement", slug:"kmp-leverage", slides:9, type:"Editorial Deck", tags:["kotlin","kmp","mobile"], lang:"ID", desc:"Sesi bersama Iqbal Fauzi: Mengapa KMP bukan tentang menggantikan Flutter, melainkan tentang leverage native codebase yang sudah ada.", color:"from-purple-600/30 to-blue-500/20", date:"2026-09-11"},
];

export const deckSlides: Record<string, DeckSlide[]> = {
  "cron-jobs-101":[
    {layout:"cover", subtitle:"Five Asterisks And A Command", title:"Cron Jobs, Explained", message:"If you keep running scripts manually, you are the cron job. This deck fixes that in nine slides.", points:["Designed for engineers who haven't written one yet.","Same syntax that has run servers for forty years, dressed up by every modern platform."], gradient:"from-amber-500/20 via-transparent to-orange-500/15"},
    {layout:"bullets", subtitle:"If You Do It Twice, Automate It", title:"You Are Already The Cron Job", message:"Every team has the script someone runs by hand. Eventually that someone gets sick, or distracted, or quits.", points:["The daily backup that runs only when you remember.","The weekly report you email at 9am Monday because the boss expects it.","The cache cleanup that breaks production when you skip a week.","The deploy script you run twice before realising it ran the first time."], gradient:"from-zinc-800 to-zinc-900"},
    {layout:"code", subtitle:"The Whole Mental Model", title:"It's Just Schedule Plus Command", message:"A cron job is a single line. Five fields that say when, followed by what to run.", code:`# Format\n<minute> <hour> <day-of-month> <month> <day-of-week>  <command>\n\n# Run every day at 06:00\n0 6 * * *  /usr/local/bin/backup.sh\n\n# Run every Monday at 09:00\n0 9 * * 1  npm run weekly-report`, points:["Five fields. One command.","The asterisks just mean 'any value'."]},
    {layout:"code", subtitle:"Minute, Hour, Day, Month, Weekday", title:"Read It Left To Right", message:"Each column has its own range. Use a number for exact, a comma for list, a slash for interval.", code:`*  *  *  *  *  command\n|  |  |  |  |\n|  |  |  +----- day of week (0-6)\n|  |  +-------- month (1-12)\n|  +----------- day of month (1-31)\n+-------------- minute (0-59)\n\n*/15 * * * *   every 15 minutes\n0 9 * * 1-5    weekdays at 09:00`, points:["Numbers for exact, slash for stride."]},
    {layout:"code", subtitle:"Copy, Tweak, Ship", title:"Three Lines You'll Actually Write", message:"Most cron jobs are one of these three shapes.", code:`# Daily housekeeping at 03:00\n0 3 * * *  /var/scripts/rotate-logs.sh\n\n# Every five minutes weekdays\n*/5 9-17 * * 1-5  curl -fsS https://api.internal/health\n\n# First day of month at 09:00\n0 9 1 * *  node scripts/send-invoices.js`, points:["Use crontab.guru to verify before deploying.","Comment every job."]},
    {layout:"cards", subtitle:"Same Idea, Friendlier Wrappers", title:"Where Cron Lives Today", message:"You don't need to SSH into a VPS anymore.", cards:[{title:"Linux crontab",desc:"The classic. crontab -e on any Unix box.",icon:"◰"},{title:"Vercel Cron",desc:"A crons block in vercel.json pointing at a route.",icon:"⚡"},{title:"GitHub Actions",desc:"Workflow with a schedule trigger. Great for repo maintenance.",icon:"‹›"},{title:"App-level libs",desc:"node-cron, BullMQ, APScheduler inside your process.",icon:"⬢"}]},
    {layout:"bullets", subtitle:"Trip On These Once, Never Again", title:"The Two Things That Bite", message:"Every engineer has a story about a cron job that ran late or never.", points:["Timezone. Most cron defaults to UTC — 0 9 * * * runs at 4pm WIB.","No retries. Log everything and alert on failure.","Concurrency. Add a lock if job may overlap.","Silent success. Pipe output to a log."], gradient:"from-amber-900/20 to-zinc-900"},
    {layout:"split", subtitle:"The Job I Avoided For Five Years", title:"A Tiny Personal Story", leftTitle:"Before", leftPoints:["Every morning I ran a script by hand.","Assumed cron required special permissions.","Five asterisks looked like regex."], rightTitle:"After", rightPoints:["One Friday I typed crontab -e.","Five minutes of reading. Syntax fit on a napkin.","The next morning it ran without me."], gradient:"from-amber-500/10 to-zinc-900"},
    {layout:"bullets", subtitle:"Three Lines To Remember", title:"Takeaways", message:"The scary syntax was a tax you were paying by not learning it.", points:["Anything you do twice on a schedule belongs in cron.","Five fields, one command — fits on a sticky note.","Pick the wrapper that matches your stack."], gradient:"from-amber-500/15 via-transparent to-orange-500/10"},
  ],
  "save-claude-tokens-rtk-caveman":[
    {layout:"cover", subtitle:"Two Tiny Tools, One Habit", title:"Cut Your Claude Bill By 90%", message:"Tokens drain in two places: bash output piped back, and the model's own verbose replies.", points:["RTK filters noisy bash before it reaches the model.","Caveman compresses Claude's prose by ~75%."], gradient:"from-violet-600/30 to-fuchsia-600/20"},
    {layout:"bullets", subtitle:"Where The Bill Comes From", title:"Every Tool Call Costs", message:"A typical Claude Code session runs 80+ tool calls.", points:["git status → 40 lines, only 3 matter.","grep → 200 hits, model reads all.","Polite prose → 300 tokens of hedging."], gradient:"from-zinc-800 to-zinc-900"},
    {layout:"code", subtitle:"The First Filter", title:"RTK — Rust Token Killer", message:"A tiny CLI proxy that sits between bash and the model.", code:`# Install\ncargo install rtk\n\n# Wrap any command\nrtk -- git status\nrtk -- grep -r \"TODO\" src/\n\n# Output before: 1800 tokens\n# Output after: 180 tokens`, points:["Trims output before it counts.","10 minutes setup, 90% off forever."]},
    {layout:"code", subtitle:"The Second Filter", title:"Caveman Mode", message:"A communication skill that rewrites Claude's replies into terse bullets.", code:`// Before: 250 tokens\n\"I'd be happy to help! Let me explain...\"\n\n// After: 45 tokens\n\"- Fixed auth bug at src/auth.ts:42\n- Added retry with backoff\n- Test: npm test -- auth\"`, points:["Cuts reply tokens ~75%.","Keeps signal, drops ceremony."]},
    {layout:"cards", subtitle:"The Habit That Ties It", title:"Stop Narrating Tools", message:"Don't let Claude describe every tool call.", cards:[{title:"RTK",desc:"Filters bash noise before model.",icon:"◰"},{title:"Caveman",desc:"Compresses prose after model.",icon:"✦"},{title:"Habit",desc:"Answer, don't narrate.",icon:"↻"},{title:"Result",desc:"90% cheaper, faster sessions.",icon:"✓"}]},
    {layout:"bullets", subtitle:"What You Keep", title:"Signal Over Ceremony", message:"You still get full reasoning — just without filler.", points:["Fix location with file:line","Why it broke","Exact edit to apply"], gradient:"from-violet-900/20 to-zinc-900"},
    {layout:"split", subtitle:"Before / After Bill", title:"One Session, Two Bills", leftTitle:"Before RTK+Caveman", leftPoints:["Avg session 120k tokens","~$1.80 per session","20 sessions → $36"], rightTitle:"After", rightPoints:["Avg session 12k tokens","~$0.18 per session","20 sessions → $3.60"], gradient:"from-violet-600/20 to-zinc-900"},
    {layout:"bullets", subtitle:"Setup In Ten Minutes", title:"Try It Today", message:"Add two tools, change one prompt.", points:["Install RTK, prefix bash calls.","Add Caveman as a skill.","Tell Claude: 'Be brief. No preamble.'"], gradient:"from-fuchsia-600/20 to-zinc-900"},
    {layout:"bullets", subtitle:"Keep The Savings", title:"Takeaways", message:"Small proxies compound fast.", points:["Filter before the model, compress after.","Cost is a design choice.","Your next session can be 90% cheaper."], gradient:"from-violet-500/20 to-zinc-900"},
  ],
  "css-container-queries":[
    {layout:"cover", subtitle:"Container Queries & The Em Cascade", title:"Components That Scale Like Images", message:"A small CSS pattern that lets a component look identical at every size.", points:["No media queries. No JS.","Three features composed: container-type, cqi, em cascade."], gradient:"from-emerald-600/25 to-teal-600/20"},
    {layout:"bullets", subtitle:"The Problem With Breakpoints", title:"Media Queries Leak", message:"A card that looks great in a hero breaks in a sidebar.", points:["Parent width matters, not viewport.","Breakpoints couple components to page.","You end up with 6 variants."], gradient:"from-zinc-800 to-zinc-900"},
    {layout:"code", subtitle:"The One-Line Fix", title:"Container-Type", message:"Tell the browser: this element is a query container.", code:`/* Parent */\n.card {\n  container-type: inline-size;\n}\n\n/* Child — now relative to parent, not viewport */\n@container (min-width: 400px) {\n  .card h3 { font-size: 1.25em; }\n}`, points:["One property on the wrapper.","Children query the parent."]},
    {layout:"code", subtitle:"Fluid Without Media Queries", title:"CQI Units", message:"cqi = 1% of container inline size. Scales like viewBox.", code:`.card {\n  padding: 4cqi;\n  gap: 2cqi;\n}\n/* 400px container → 16px padding\n   800px container → 32px padding\n   Same ratio, automatically */`, points:["No breakpoints, just ratios.","Works inside any layout."]},
    {layout:"code", subtitle:"The Cascade Trick", title:"Em Does The Rest", message:"Set font-size in cqi, let em scale everything else.", code:`.card { font-size: 4cqi; }\n.card h3 { font-size: 1.5em; }\n.card p  { font-size: 0.875em; }\n/* Change one value, entire card scales like an image */`, points:["One source of scale.","Typography, spacing, icons all follow."]},
    {layout:"cards", subtitle:"Put Together", title:"The Pattern", message:"Three lines that replace a breakpoint file.", cards:[{title:"container-type",desc:"Makes element queryable.",icon:"▦"},{title:"cqi",desc:"Fluid unit tied to container.",icon:"↔"},{title:"em",desc:"Cascade scales children.",icon:"↕"},{title:"Result",desc:"Image-like scaling, no JS.",icon:"✓"}]},
    {layout:"bullets", subtitle:"Where It Shines", title:"Design Systems", message:"Cards, dashboards, embeds — anywhere a component appears at multiple widths.", points:["Sidebar vs main column.","Mobile drawer vs desktop grid.","Figma component → CSS parity."], gradient:"from-emerald-900/20 to-zinc-900"},
    {layout:"split", subtitle:"Before / After", title:"Same Component, Two Contexts", leftTitle:"Media queries", leftPoints:["Looks wrong in sidebar","Add breakpoint override","Override the override"], rightTitle:"Container + cqi + em", rightPoints:["Looks right everywhere","One scaling rule","Copy-paste to new context"], gradient:"from-emerald-600/20 to-zinc-900"},
    {layout:"bullets", subtitle:"Try It In Five Minutes", title:"Takeaways", message:"Make your next card behave like an image.", points:["container-type on wrapper.","font-size in cqi, rest in em.","Reuse beats responsive."], gradient:"from-teal-600/20 to-zinc-900"},
  ],
  "kmp-leverage":[
    {layout:"cover", subtitle:"Sesi Bersama Iqbal Fauzi, Bobobox", title:"Kotlin Multiplatform: Leverage, Not Replacement", message:"KMP bukan tentang menggantikan Flutter. Ia tentang membuat apa yang sudah ada menjadi lebih powerful.", points:["Shared logic, native UI.","Incremental migration tanpa rewrite.","Leverage existing native codebase."], gradient:"from-purple-600/30 to-blue-500/20"},
    {layout:"bullets", subtitle:"Dua Pertanyaan, Bukan Satu", title:"Speed Yang Sebenarnya", message:"Saat demo langsung, KMP menunjukkan 10x lebih cepat bahkan di device low-end.", points:["Pertanyaan lama: seberapa cepat kita menulis code?","Pertanyaan baru: seberapa baik hasilnya saat dijalankan?","KMP menjawab keduanya."], gradient:"from-zinc-800 to-zinc-900"},
    {layout:"cards", subtitle:"Apa Yang Di-share", title:"Shared Logic, Native UI", message:"KMP memungkinkan berbagi bagian yang masuk akal tanpa memaksa UI menjadi abstraksi.", cards:[{title:"Business logic",desc:"Validasi, domain logic, aturan bisnis.",icon:"◰"},{title:"Networking",desc:"API calls, request handling.",icon:"↔"},{title:"Data layer",desc:"Database, persistence.",icon:"▦"},{title:"Native UI",desc:"Platform-specific, pixel-perfect.",icon:"✓"}]},
    {layout:"bullets", subtitle:"Value Terbesar KMP", title:"Incremental Migration", message:"Untuk tim dengan investasi besar di native Android + iOS, KMP tidak memaksa rewrite.", points:["Bisa masuk per modul, tidak sekaligus.","Mulai dari bagian yang paling memberikan value.","Migrasi bertahap tanpa risiko besar.","Codebase lama tetap hidup, tidak buang."], gradient:"from-purple-900/20 to-zinc-900"},
    {layout:"split", subtitle:"KMP vs Flutter: False Binary", title:"Bukan Pertanyaan Winner-Take-All", leftTitle:"Flutter Tetap Kuat Untuk", leftPoints:["Cross-platform UI + development cepat.","Satu codebase dari nol.","Tim yang memulai dari nol."], rightTitle:"KMP Untuk", rightPoints:["Shared logic + native UI.","Native ecosystem depth.","Tim dengan codebase native yang ada."], gradient:"from-purple-600/20 to-zinc-900"},
    {layout:"bullets", subtitle:"Pertanyaan Yang Tepat", title:"Problem First", message:"Pilih berdasarkan masalah Anda, bukan hype.", points:["Problem kita apa?","Codebase kita sekarang seperti apa?","Pendekatan mana yang memberikan leverage terbesar?","Solusi terbaik mungkin bukan mengganti semuanya, tapi membuat yang ada jadi lebih powerful."], gradient:"from-zinc-800 to-zinc-900"},
    {layout:"code", subtitle:"Realistic For Real Teams", title:"Incremental Path", message:"Tidak perlu rewrite di hari pertama.", code:"/* Hari 1: Buat KMP module baru */\nsharedModule/ { data, domain }\n\n/* Hari 7: Integrasikan ke Android */\n/* Hari 14: Integrasikan ke iOS */\n/* Minggu depan: Modul berikutnya */", points:["Validasi dengan satu platform dulu.","Pecah ke modul kecil, bukan monolith."]},
    {layout:"bullets", subtitle:"Key Takeaway", title:"From Iqbal", message:"Demo bukan slide — kode dijalankan langsung, hasilnya terlihat real-time.", points:["Speed bukan hanya tentang keyboard.","Incremental migration adalah moat bisnis KMP.","Tidak kill Flutter — complementary approach.","Evaluate based on your actual constraints."], gradient:"from-purple-500/20 to-zinc-900"},
    {layout:"bullets", subtitle:"Kesimpulan", title:"Terima kasih Iqbal Fauzi", message:"Leverage existing, leverage native ecosystem, leverage team expertise.", points:["Pertanyaan pertama: what problem?","Baru kemudian: which framework?","Sometimes the answer is not replacing.","It's making what you have more powerful."], gradient:"from-purple-600/20 to-blue-500/10"},
  ],
  "rubiks-cube-101":[
    {layout:"cover", subtitle:"History • Beginner Solve • The Rabbit Hole", title:"Rubik’s Cube 101", message:"18 slides from invention to your first solve. No speed required.", points:["1974 Hungary → 2026 you.","Designed for first-timers."], gradient:"from-sky-500/25 to-blue-600/20"},
    {layout:"bullets", subtitle:"1974 → Today", title:"A 50-Year Puzzle", message:"Ernő Rubik built a twistable cube to teach geometry.", points:["43 quintillion possible states.","Only one solved.","World record: 3.13 seconds (Max Park)."], gradient:"from-zinc-800 to-zinc-900"},
    {layout:"cards", subtitle:"Anatomy", title:"Know The Pieces", message:"Six faces, nine stickers each, but only three piece types.", cards:[{title:"Center",desc:"Fixed color, defines face.",icon:"⬢"},{title:"Edge",desc:"Two colors, 12 pieces.",icon:"▭"},{title:"Corner",desc:"Three colors, 8 pieces.",icon:"⬣"},{title:"Cubies",desc:"20 moving + 6 centers.",icon:"◰"}]},
    {layout:"bullets", subtitle:"Notation Without Pain", title:"Letters = Turns", message:"U, D, F, B, L, R — clockwise. Add ' for counter-clockwise.", points:["R = right face clockwise.","R' = counter, R2 = double.","Sequence: R U R' U' (sexy move)."], gradient:"from-sky-900/20 to-zinc-900"},
    {layout:"code", subtitle:"The Only Algorithm You Need First", title:"White Cross", message:"Solve white edges around white center.", code:`1. Find white edge\n2. Bring to top with R / F\n3. Align with center color\n4. Turn face down: F2\n\nRepeat 4×`, points:["Intuitive, not memorized.","Center color guides placement."]},
    {layout:"bullets", subtitle:"Layer by Layer", title:"First Two Layers", message:"Four slots, same 8-move loop.", points:["Find white corner in bottom.","Use R' D' R D until on top.","Position over slot, then U R U' R'."], gradient:"from-zinc-800 to-zinc-900"},
    {layout:"split", subtitle:"The Last Layer Intro", title:"Yellow Cross → Corners", leftTitle:"Cross", leftPoints:["F R U R' U' F'","Repeat until cross."], rightTitle:"Corners", rightPoints:["R U R' U R U2 R'","Cycle until solved."], gradient:"from-sky-500/20 to-zinc-900"},
    {layout:"bullets", subtitle:"Practice Loop", title:"Your Weekend Plan", message:"One hour Saturday, one hour Sunday.", points:["Scramble, solve white cross 10×.","Add corners, repeat.","Time yourself — watch it halve."], gradient:"from-blue-900/20 to-zinc-900"},
    {layout:"bullets", subtitle:"Welcome To The Hobby", title:"Beyond Beginner", message:"Faster methods, lubricants, new puzzles.", points:["CFOP, Roux, ZZ.","Magnetic cubes.","From 10 minutes to 1 minute."], gradient:"from-sky-500/20 to-zinc-900"},
  ],
  "mobile-frameworks":[
    {layout:"cover", subtitle:"Strategic Overview", title:"Mobile Frameworks in 2026", message:"React Native, Flutter, KMP, Native, Hybrid — which wins for your team?", points:["No universal winner.","Winner for your timeline and team."], gradient:"from-zinc-700/30 to-zinc-900"},
    {layout:"cards", subtitle:"Landscape", title:"Five Contenders", message:"Every option trades hiring speed for platform fidelity.", cards:[{title:"React Native",desc:"JS/TS, Expo, huge hiring pool.",icon:"⚛"},{title:"Flutter",desc:"Dart, pixel-perfect, fast.",icon:"◯"},{title:"KMP",desc:"Kotlin, shared logic only.",icon:"K"},{title:"Native",desc:"Swift/Kotlin, full platform.",icon:""}]},
    {layout:"bullets", subtitle:"Hiring Reality", title:"Who Can You Hire?", message:"Framework choice is often team choice.", points:["RN: every web team can try.","Flutter: needs Dart ramp.","Native: two teams, two backlogs.","KMP: Kotlin on both."], gradient:"from-zinc-800 to-zinc-900"},
    {layout:"split", subtitle:"Performance Envelope", title:"What Actually Feels Native?", leftTitle:"60fps Easy", leftPoints:["Flutter : consistent.","Native : best with tuning."], rightTitle:"Needs Care", rightPoints:["RN : bridge, JSI improves.","Hybrid : WebView limits."], gradient:"from-zinc-700/30 to-zinc-900"},
    {layout:"bullets", subtitle:"Shared Code Sweet Spot", title:"How Much Can You Share?", message:"100% sounds nice until platform specifics hit.", points:["UI 60-80% share typical.","Logic 90%+ is easy.","Platform APIs always leak."], gradient:"from-zinc-800 to-zinc-900"},
    {layout:"code", subtitle:"Real Stack Example", title:"Crossword Family (RN + Expo)", message:"One monorepo, four apps, thin shells.", code:`apps/crosswords-shared/\n  engine/  ← shared\n  ui/      ← shared\napps/word-cross/   ← shell\napps/kids-cross/   ← shell`, points:["Engine + UI shared.","Per app: icon, copy, monetization."]},
    {layout:"bullets", subtitle:"Cost Lens", title:"Build vs Maintain", message:"Cheaper to build ≠ cheaper to maintain.", points:["RN/Flutter: one team → lower burn.","Native: two teams → higher but fewer edge cases.","KMP: one language, two UIs."], gradient:"from-zinc-700/20 to-zinc-900"},
    {layout:"cards", subtitle:"Risk Map", title:"Where Each Stumbles", message:"Choose the risk you prefer to manage.", cards:[{title:"RN",desc:"Metro, native deps.",icon:"!"},{title:"Flutter",desc:"Dart niche, app size.",icon:"!"},{title:"KMP",desc:"iOS interop still young.",icon:"!"},{title:"Native",desc:"Double cost, drift.",icon:"!"}]},
    {layout:"bullets", subtitle:"Decision Rule", title:"Pick For Your Team", message:"Timeline, hiring, platform needs — in that order.", points:["Web team? → RN.","Design-critical? → Flutter.","Kotlin lovers? → KMP.","Platform depth? → Native."], gradient:"from-zinc-700/20 to-zinc-900"},
  ],
  "ai-coding-agent":[
    {layout:"cover", subtitle:"From Assistant to Execution System", title:"AI Coding Agent", message:"How agents actually work: when to use them, how to prompt them, and what guardrails keep speed from chaos.", points:["Not autocomplete.","An execution system."], gradient:"from-purple-600/25 to-indigo-600/20"},
    {layout:"bullets", subtitle:"Beyond Chat", title:"What 'Agent' Means", message:"An agent loops: plan → act → observe → repeat.", points:["Chat answers. Agent executes.","Tools = its hands.","Context = its memory."], gradient:"from-zinc-800 to-zinc-900"},
    {layout:"cards", subtitle:"Loop", title:"Sense → Decide → Act", message:"Every turn compresses feedback.", cards:[{title:"Plan",desc:"Decompose task.",icon:"P"},{title:"Act",desc:"Edit, run, test.",icon:"A"},{title:"Observe",desc:"Read output.",icon:"O"},{title:"Adjust",desc:"Fix, retry.",icon:"↻"}]},
    {layout:"code", subtitle:"Prompt That Works", title:"Guardrails In Prompt", message:"Agents obey boundaries you set.", code:`You are a senior engineer.\n- Keep edits minimal\n- Run tests after each change\n- Never commit secrets\n- Ask before large refactors`, points:["Short, explicit, testable.","Constraints beat creativity."]},
    {layout:"bullets", subtitle:"When To Use", title:"Two Sweet Spots", message:"Speed with safety.", points:["Repetitive migration across many files.","Feature slice: spec → code → test."], gradient:"from-zinc-800 to-zinc-900"},
    {layout:"split", subtitle:"Speed vs Chaos", title:"Keep It Safe", leftTitle:"Without Guardrails", leftPoints:["Edits 20 files at once"," invents APIs"," breaks tests quietly"], rightTitle:"With Guardrails", rightPoints:["One file at a time"," reuses existing APIs"," fails loudly on test"], gradient:"from-purple-600/20 to-zinc-900"},
    {layout:"bullets", subtitle:"Human In Loop", title:"You Are The Reviewer", message:"Agent writes draft, you decide.", points:["Approve each diff.","Run real device tests.","Keep product judgment."], gradient:"from-zinc-800 to-zinc-900"},
    {layout:"code", subtitle:"Session Pattern", title:"A Daily Flow", message:"One terminal, tight loop.", code:`/brief → agent plans\n/agent edits src/**\nagent runs: npm test\nYou: review diff\n/agent iterates`, points:["Narrate less, verify more.","RTK + Caveman helps here too."]},
    {layout:"bullets", subtitle:"Start Small", title:"Takeaways", message:"Agents amplify taste.", points:["Good taste → fast ship.","Vague taste → confident garbage.","Start with one repo, one task."], gradient:"from-purple-500/20 to-zinc-900"},
  ],
};

export const postsData: Post[] = [
  {title:"Stop Burning Claude Credits", slug:"save-claude-tokens-rtk-caveman", tag:"tips", date:"2026-05-18", desc:"Every git status, every grep, every paragraph of polite prose costs tokens. Two tools cut a normal session's bill by 90%. Setup takes ten minutes.", color:"bg-white text-black", accent:"tips"},
  {title:"Stop Running Things Manually", slug:"cron-jobs-in-five-minutes", tag:"tips", date:"2026-05-18", desc:"If you keep opening the terminal to run the same command on the same schedule, you are the cron job. It's time to fix that.", color:"bg-zinc-900 text-white border border-zinc-800", accent:"tips"},
  {title:"Components That Scale", slug:"css-container-queries", tag:"css", date:"2026-05-15", desc:"Stop using media queries when you need a component to look right in a sidebar AND a hero. There's a one-line fix.", color:"bg-white text-black", accent:"css"},
  {title:"Your AI Is Not Autocomplete", slug:"ai-coding-agent-operating-model", tag:"coding", date:"2026-05-14", desc:"It's a fast junior who needs direction. Get it right and you ship faster. Get it wrong and you ship confident garbage.", color:"bg-zinc-900 text-white border border-zinc-800", accent:"coding"},
  {title:"Pick Your Mobile Stack", slug:"mobile-frameworks-2026", tag:"tips", date:"2026-05-10", desc:"There's no universal winner. Only a winner for your team, your timeline, and the product you're actually building.", color:"bg-white text-black", accent:"tips"},
  {title:"You Can Solve The Cube", slug:"rubiks-cube-beginner-flow", tag:"hobby", date:"2026-05-08", desc:"Not in 20 seconds. But in a weekend. The trick is to stop trusting your instincts and start trusting layers.", color:"bg-zinc-900 text-white border border-zinc-800", accent:"hobby"},
  {title:"Kotlin Multiplatform: Leverage, Not Replacement", slug:"kmp-leverage-post", tag:"mobile", date:"2026-09-11", desc:"KMP bukan tentang menggantikan Flutter, melainkan leverage native codebase yang sudah ada. Sesi demo bersama Iqbal Fauzi.", color:"bg-white text-black", accent:"mobile"},
];

export const postsSlides: Record<string, PostSlide[]> = {
  "cron-jobs-in-five-minutes":[
    {num:"", label:"tips", title:"Stop Running Things Manually", subtitle:"", body:"If you keep opening the terminal to run the same command on the same schedule, you are the cron job. It's time to fix that.", theme:"black"},
    {num:"02", label:"The Pain", title:"You Are Already The Cron Job", body:"Every morning. Every Friday. Every deploy. You SSH in, run the thing, close the window. Until you forget once, and now there's an incident.", bullets:["Daily backup you keep meaning to script.","Cleanup that fails when you go on holiday.","Manual reports that should email themselves."], theme:"black"},
    {num:"03", label:"The Idea", title:"It's Just A Schedule + Command", body:"A cron job is one line. Five fields that say when, followed by the command. The whole thing is shorter than this body text.", code:"# Run every day at 6am\n0 6 * * *  /usr/local/bin/backup.sh\n\n# Run every Monday at 9am\n0 9 * * 1  npm run weekly-report", theme:"black"},
    {num:"04", label:"The Syntax", title:"Five Asterisks, Read Left To Right", body:"Minute, hour, day-of-month, month, day-of-week. Use a number, a list, or a star for any. That's the whole language.", code:"*  *  *  *  *  command\n|  |  |  |  |\n|  |  |  |  +-- day of week (0-6, Sun=0)\n|  |  |  +----- month (1-12)\n|  |  +-------- day of month (1-31)\n|  +----------- hour (0-23)\n+-------------- minute (0-59)", theme:"black"},
    {num:"05", label:"Where It Lives", title:"Pick The Wrapper That Fits", body:"The five asterisks haven't changed in decades. What changes is where you put them. Modern platforms hide the server entirely.", bullets:["Linux: crontab -e on your VPS.","Vercel: vercel.json `crons` block.","GitHub Actions: schedule trigger on workflow.","App-level: node-cron, BullMQ, Sidekiq."], theme:"black"},
    {num:"06", label:"Gotchas", title:"Two Things That Will Bite", body:"Almost everyone trips on the same two issues the first time. Knowing them upfront saves an hour of confusion.", bullets:["Timezone: most cron is UTC by default.","No retries: if it fails, it just fails.","Log everything. Cron runs silently."], theme:"black"},
    {num:"07", label:"Closing", title:"Five Asterisks. That's The Whole Wall.", body:"The syntax looked scary, so you ran things by hand. Five minutes of learning it pays back every week for the rest of your career.", bullets:["If you do it twice, automate it.","Start with one daily job. Build from there."], theme:"black"},
  ],
  "save-claude-tokens-rtk-caveman":[
    {num:"", label:"tips", title:"Stop Burning Claude Credits", body:"Every git status, every grep, every paragraph of polite prose costs tokens. Two tools cut a normal session's bill by 90%. Setup takes ten minutes.", theme:"white"},
    {num:"02", label:"Where Tokens Go", title:"It's Not The Code", body:"Look at any long session and the cost lives in two places. Bash output piped back to the model, and the model's own verbose explanations.", bullets:["git status returns 200 lines. You needed 5.","Replies open with 'Great question!' every time.","Build logs eat half a context window."], theme:"white"},
    {num:"03", label:"Tool 1", title:"RTK Filters Bash Before It Speaks", body:"Rust Token Killer is a CLI proxy. It runs your commands, strips noise, and hands the model only the parts that matter.", code:"# Install once\nbrew install rtk\n\n# Verify\nrtk --version\nrtk gain   # see lifetime savings", theme:"white"},
    {num:"04", label:"Tool 2", title:"Caveman Compresses Replies", body:"Caveman is a skill that tells Claude to drop filler. Same answers, 75% fewer words.", code:"# Turn on\n/caveman\n\n# Or save forever in\n~/.claude/CLAUDE.md\n\n# Levels: lite, full, ultra", theme:"white"},
    {num:"05", label:"Combined Effect", title:"Roughly 90% Off", body:"RTK cuts the input side. Caveman cuts the output side. Together they drop a typical session from 200k tokens to under 25k.", bullets:["RTK: 60 to 90% off bash output.","Caveman: ~75% off model prose.","Compound: 90%+ off the whole session."], theme:"white"},
    {num:"06", label:"Gotchas", title:"Two Things To Know", body:"RTK is opinionated about find syntax and a few other commands. Caveman keeps tech accuracy but can read terse to newcomers.", bullets:["RTK rejects compound find predicates.","Caveman ultra reads blunt. Use lite for shared chats.","Both have a proxy escape hatch when needed."], theme:"white"},
    {num:"07", label:"Closing", title:"Ten Minutes, Months Of Credits", body:"Install both tonight. Tomorrow's first session uses 10% of what last week's did.", bullets:["RTK = brew install. Hook handles the rest.","Caveman = one line in CLAUDE.md."], theme:"white"},
  ],
  "css-container-queries":[
    {num:"", label:"css", title:"Components That Scale", body:"Stop using media queries when you need a component to look right in a sidebar AND a hero. There's a one-line fix, and it changes how you write CSS.", theme:"white"},
    {num:"02", label:"The Problem", title:"Media Queries Miss The Point", body:"The same card might live in a 250px sidebar and a 900px hero. Media queries don't know which.", bullets:["Components live in many widths.","Viewport size is the wrong signal.","Breakpoint guesswork never ends."], theme:"white"},
    {num:"03", label:"The Tool", title:"Ask Your Parent's Size", body:"Declare a container, and its descendants can finally ask: how big is my parent right now?", code:".card {\n  /* I am a container.\n     Track my width. */\n  container-type: inline-size;\n}", theme:"white"},
    {num:"04", label:"The Units", title:"1cqi = 1% Of Container", body:"Like vw and vh, but anchored to the container instead of the viewport. Sizes scale linearly with whatever box you're inside.", code:".card .title {\n  font-size: 4cqi;   /* 4% of card width */\n  padding: 2cqi;\n}\n/* card 400px wide -> 16px\n   card 800px wide -> 32px */", theme:"white"},
    {num:"05", label:"The Pattern", title:"One Knob, Whole Composition", body:"Set font-size at the root in cqi. Use em for everything else. The component now scales like an SVG, except it's just HTML and CSS.", code:".card .inner {\n  font-size: 4cqi;\n}\n.title  { font-size: 2.5em; }\n.body   { font-size: 0.9em; }\n.avatar { height: 1.4em; }\n.grid   { gap: 1.5em; }", theme:"white"},
    {num:"06", label:"Gotcha", title:"It Can't Query Itself", body:"The first time you try this, it breaks. cqi skips past the element it's declared on. You need two: one declares the container, one consumes it.", code:"/* WRONG. cqi resolves\n   against the viewport */\n.card {\n  container-type: inline-size;\n  font-size: 4cqi;\n}\n\n/* RIGHT. Split into two */\n.card  { container-type: inline-size; }\n.inner { font-size: 4cqi; }", theme:"white"},
    {num:"07", label:"Closing", title:"Use For Reusable UI", body:"Cards, badges, slide previews. Anything that travels between widths. Skip it for body copy.", bullets:["Great for: components, widgets, tiles.","Skip for: articles, long-form prose.","Hybrid: pair cqi with clamp()."], theme:"white"},
  ],
  "ai-coding-agent-operating-model":[
    {num:"", label:"coding", title:"Your AI Is Not Autocomplete", body:"It's a fast junior who needs direction. Get it right and you ship faster. Get it wrong and you ship confident garbage.", theme:"black"},
    {num:"02", label:"The Shift", title:"It Reads, Runs, Recovers", body:"Today's agents touch your filesystem, run your tests, and fix their own mistakes.", bullets:["Edits across many files in one pass.","Reads errors, retries, self-corrects.","Still hallucinates without context."], theme:"black"},
    {num:"03", label:"Where It Shines", title:"Boring Work, Verifiable Wins", body:"AI is happiest with scoped tasks where you can tell if it's right in under 60 seconds.", bullets:["UI from an approved design spec.","Refactors with tests as a safety net.","Docs, summaries, repetitive cleanup."], theme:"black"},
    {num:"04", label:"Where It Breaks", title:"It's Not A Senior Engineer", body:"Hand it vague intent and you'll get confident wrongness.", bullets:["Fails when the goal isn't clear.","Wants one task, not your whole sprint.","You're still the architect. Always."], theme:"black"},
    {num:"05", label:"What Works", title:"Tight Loops Beat Big Prompts", body:"Prompt, run, check, adjust. Fast. The agent gets useful exactly when feedback is cheap and quick.", bullets:["Feed it repo, files, constraints.","Run tests after every small change.","Many small loops beat one mega-prompt."], theme:"black"},
    {num:"06", label:"The Mindset", title:"Design The System, Not The Code", body:"Great teams don't toss prompts and pray. They build an environment where good output is the default.", bullets:["Clear instructions = better first drafts.","Review habits keep the speed honest."], theme:"black"},
  ],
  "mobile-frameworks-2026":[
    {num:"", label:"tips", title:"Pick Your Mobile Stack", body:"There's no universal winner. Only a winner for your team, your timeline, and the product you're actually building.", theme:"white"},
    {num:"02", label:"Decision Inputs", title:"Start With Constraints", body:"Most framework debates skip the only question that matters. What does YOUR team need to ship? By when? With whom?", bullets:["Timeline and hiring runway.","Performance and native depth needs.","How much platform-specific work?"], theme:"white"},
    {num:"03", label:"React Native", title:"Best For Web-Heavy Teams", body:"If you already ship React on the web, RN gives you a mobile app without hiring new humans.", bullets:["Real skill transfer from web to mobile.","Mature ecosystem, huge community.","Fast default for product-led teams."], theme:"white"},
    {num:"04", label:"Flutter", title:"Best For Pixel Control", body:"Flutter shines when the UI IS the product. Same render on every device. But yes, you'll learn Dart.", bullets:["Identical visuals across devices.","Strong for design-led apps.","Confirm Dart works for your team."], theme:"white"},
    {num:"05", label:"Native Paths", title:"Best For Deep Platform Work", body:"When the product IS the integration (watches, AR, top-100 apps), native wins.", bullets:["Built for platform-first roadmaps.","Higher specialization cost upfront.","Worth it when native is the moat."], theme:"white"},
    {num:"06", label:"Closing", title:"Fit Wins, Hype Loses", body:"The loudest framework wins on Twitter. The right framework ships your product.", bullets:["Business goals first.","Team capability second.","Framework preference last."], theme:"white"},
  ],
  "rubiks-cube-beginner-flow":[
    {num:"", label:"hobby", title:"You Can Solve The Cube", body:"Not in 20 seconds. But in a weekend. The trick is to stop trusting your instincts and start trusting layers.", theme:"black"},
    {num:"02", label:"Step 1", title:"Start With The Cross", body:"Forget the rest of the cube exists. Just line up four white edges with the matching centers.", bullets:["Ignore the corners. Completely.","Accuracy beats speed every time."], theme:"black"},
    {num:"03", label:"Step 2", title:"Build The First Layer", body:"Now slot in the four white corners, one at a time. You'll mess up. That's literally how your hands learn.", bullets:["Check side colors before locking in.","Undoing mistakes is the work."], theme:"black"},
    {num:"04", label:"Step 3", title:"Slip In The Middle Edges", body:"Two algorithms, mirror images of each other. Don't memorize them. Feel the rhythm. Up, around, down.", bullets:["One edge at a time. Slow it down.","Repeat until it stops feeling weird."], theme:"black"},
    {num:"05", label:"Step 4", title:"Crack The Last Layer", body:"This is where everyone gets stuck. The secret: recognize the pattern first, then trust the sequence.", bullets:["Orient the top face before permuting.","Trust the algorithm. It works."], theme:"black"},
    {num:"06", label:"Closing", title:"Habits Beat Panic-Twisting", body:"Beginners who slow down learn fastest. The cube rewards calm hands and clean patterns way more than speed.", bullets:["Same sequence every session.","Recognize patterns; don't memorize."], theme:"black"},
  ],
  "kmp-leverage-post":[
    {num:"", label:"mobile", title:"KMP: Leverage, Not Replacement", body:"Datang ingin tahu KMP. Pulang kepikiran: ternyata positioning-nya sangat berbeda dari yang saya bayangkan.", theme:"white"},
    {num:"02", label:"Dua Pertanyaan", title:"Speed Yang Sesungguhnya", body:"Di sesi Iqbal Fauzi, KMP didemo langsung di device low-end. Bukan slide. Bukan klaim. Langsung dijalankan.", bullets:["Seberapa cepat kita menulis code?","Seberapa baik hasilnya saat dijalankan?","KMP menjawab keduanya sekaligus."], theme:"white"},
    {num:"03", label:"Shared Logic", title:"Share Yang Masuk Akal", body:"KMP tidak memaksa UI menjadi abstraksi. Anda share bagian yang memang layak di-share.", bullets:["Business logic & domain rules.","Networking & data layer.","Validation & state management.","UI? Tetap native, tetap platform-specific."], theme:"white"},
    {num:"04", label:"Nilai Bisnis Terbesar", title:"Incremental Migration", body:"Untuk perusahaan dengan investasi besar di native Android dan iOS, KMP tidak memaksa rewrite dari nol.", bullets:["Masuk per modul, bukan big-bang migration.","Mulai dari bagian yang paling memberikan value.","Tidak buang codebase lama.","Tidak ambil risiko migrasi sekaligus."], theme:"white"},
    {num:"05", label:"False Binary", title:"KMP Tidak Akan Membunuh Flutter", body:"Pertanyaannya bukan siapa yang menang. Pertanyaannya adalah: problem Anda apa?", bullets:["Flutter: cross-platform UI, satu codebase, mulai dari nol.","KMP: shared logic, native UI, leverage existing codebase.","Dua pendekatan berbeda untuk dua konteks berbeda."], theme:"white"},
    {num:"06", label:"Framework Selection", title:"Problem First, Framework Second", body:"Solusi terbaik kadang bukan mengganti semuanya — tapi membuat yang sudah ada menjadi lebih powerful.", bullets:["Codebase Anda sekarang seperti apa?","Berapa besar investasi yang sudah ada di native?","Framework mana yang memberi leverage terbesar?"], theme:"white"},
    {num:"07", label:"Terima kasih Iqbal Fauzi", title:"Closing", body:"Insight dan demo dari Iqbal Fauzi, Senior Mobile Developer di Bobobox. KMP sebagai opsi realistis, bukan sekadar teori.", bullets:["KotlinMultiplatform #KMP #Flutter.","#MobileDevelopment #SoftwareEngineering.","Evaluate based on your actual constraints."], theme:"white"},
  ],
};

export const blogData: BlogPost[] = [
  {title:"From four repos to a monorepo", slug:"four-repos-to-a-monorepo", date:"2026-06-21", mins:3, tags:["monorepo","Expo","Metro","refactor","architecture"], excerpt:"Consolidating four byte-identical app repos into one shared core plus thin app shells, the expo-router and Metro problems it surfaced, and validating the migration with real bundles.", featured:true},
  {title:"Shipping, then listening", slug:"shipping-then-listening", date:"2026-06-20", mins:3, tags:["UX","feedback","mobile","indie"], excerpt:"The first round of real tester feedback and the small, high-leverage fixes it produced: grid spacing, free typing, jump buttons, easing early ads, and a well-timed review prompt."},
  {title:"The Play Store gauntlet", slug:"the-play-store-gauntlet", date:"2026-06-19", mins:3, tags:["Google Play","launch","mobile","indie"], excerpt:"Everything between a finished app and a live listing: store assets, data safety, content rating, the target-audience trap, app-ads.txt, and the testing tracks."},
  {title:"A cross-app discount with no backend", slug:"cross-app-discount-no-backend", date:"2026-06-18", mins:3, tags:["architecture","RevenueCat","deep linking","mobile"], excerpt:"Giving players 50% off in a sibling app when they already paid in one, using a deep-link handshake instead of sign-in."},
  {title:"Mobile in-app purchases: what nobody warns you about", slug:"mobile-iap-what-nobody-warns-you-about", date:"2026-06-17", mins:3, tags:["RevenueCat","AdMob","Google Play","monetization","mobile"], excerpt:"AdMob, RevenueCat, and Google Play Billing in practice. Products versus entitlements versus offerings, the 'purchase unavailable' debugging."},
  {title:"A hint economy that's fair but not free", slug:"a-fair-hint-economy", date:"2026-06-16", mins:3, tags:["game design","monetization","React Native"], excerpt:"Designing hints that monetize without feeling hostile: a regenerating free tier, never-expiring bonus hints, streak rewards."},
  {title:"Building a crossword engine in React Native", slug:"building-a-crossword-engine-react-native", date:"2026-06-15", mins:3, tags:["React Native","Expo","gestures","game dev"], excerpt:"Exact-hit-test tappable cells, pinch-zoom with breathing room, an interlocking offline level generator."},
  {title:"One idea, four apps", slug:"one-idea-four-apps", date:"2026-06-14", mins:3, tags:["product","architecture","Expo","mobile"], excerpt:"The product and architecture bet behind shipping a family of four themed crossword games from a single shared codebase."},
  {title:"Building four apps with an AI coding agent", slug:"building-four-apps-with-an-ai-agent", date:"2026-06-13", mins:3, tags:["AI coding agent","React Native","Expo","indie","mobile"], excerpt:"How I shipped a family of four crossword games to the Play Store by pairing with an AI coding agent."},
  {title:"How I cut my Claude token bill by 90%", slug:"how-i-cut-claude-tokens-90-percent", date:"2026-05-18", mins:6, tags:["claude-code","ai","productivity"], excerpt:"Two tiny tools and one habit. RTK trims bash output before it reaches the model. Caveman trims the model's replies."},
  {title:"The cron job I avoided for five years", slug:"the-cron-job-i-avoided-for-five-years", date:"2026-05-16", mins:5, tags:["devops","automation"], excerpt:"I ran the same script by hand for years because cron looked like a foreign language. It took five minutes to learn."},
  {title:"Components that scale like images", slug:"components-that-scale-like-images", date:"2026-05-15", mins:4, tags:["css","frontend"], excerpt:"A small CSS pattern that turned out to be the missing piece: container queries plus an em cascade."},
];

export const videosData: Video[] = [
  // — dari channel UCrmuEbY204vec5E1-JZ1Z4A (@codingskuy) via youtubei/v1/browse —
  // Videos (16:9) — tab Videos
  {id:"OYlvW32U7VM", title:"Gen Z belajar Kotlin di Era AI!", desc:"Live coding Kotlin untuk Gen Z di era AI — kenapa masih relevan.", thumb:"https://i.ytimg.com/vi/OYlvW32U7VM/hq720.jpg", date:"4 weeks ago", duration:"1:08:38", views:"25", isShort:false, tag:"kotlin"},
  {id:"3xG5rPoh49I", title:"Part II - Gen Z Belajar TypeScript di Zaman AI, Masih Aman?", desc:"Lanjutan deep dive TypeScript untuk Gen Z.", thumb:"https://i.ytimg.com/vi/3xG5rPoh49I/hq720.jpg", date:"1 month ago", duration:"1:47:38", views:"5", isShort:false, tag:"typescript"},
  {id:"UzPpXbyWMJs", title:"🚀 Gen Z Belajar TypeScript di Zaman AI, Masih Aman?", desc:"Apakah TypeScript masih aman untuk Gen Z di zaman AI?", thumb:"https://i.ytimg.com/vi/UzPpXbyWMJs/hq720.jpg", date:"1 month ago", duration:"1:34:25", views:"11", isShort:false, tag:"typescript"},
  {id:"2RDMEdUmENA", title:"Who I Am?", desc:"Perkenalan — Who I Am?", thumb:"https://i.ytimg.com/vi/2RDMEdUmENA/hq720.jpg", date:"1 month ago", duration:"0:33", views:"6", isShort:false, tag:"intro"},
  {id:"y740aHNY-kw", title:"Day #7 Programmer Nganggur", desc:"Hari ke-7 perjalanan programmer nganggur.", thumb:"https://i.ytimg.com/vi/y740aHNY-kw/hq720.jpg", date:"7 months ago", duration:"47:10", views:"13", isShort:false, tag:"series"},
  {id:"PRtfeCY_px4", title:"Day #6 Programmer Nganggur", desc:"Hari ke-6 — catatan harian.", thumb:"https://i.ytimg.com/vi/PRtfeCY_px4/hq720.jpg", date:"8 months ago", duration:"46:47", views:"7", isShort:false, tag:"series"},
  {id:"lzm6EuGzoZE", title:"Day #5 Programmer Nganggur", desc:"Hari ke-5 — progress dan refleksi.", thumb:"https://i.ytimg.com/vi/lzm6EuGzoZE/hq720.jpg", date:"8 months ago", duration:"1:06:41", views:"2", isShort:false, tag:"series"},
  {id:"G5boTGk8yuk", title:"Strategi Sukses Mengatur Tim Lintas Fungsi dan Rekrutmen Anggota yang Tepat!", desc:"Strategi atur tim lintas fungsi.", thumb:"https://i.ytimg.com/vi/G5boTGk8yuk/hq720.jpg", date:"8 months ago", duration:"4:00", views:"—", isShort:false, tag:"leadership"},
  {id:"3AkVb6ryll0", title:"Framework SMART  Cara Jitu Mengelola Proyek Supaya Tujuan Mudah Tercapai!", desc:"Framework SMART untuk kelola proyek.", thumb:"https://i.ytimg.com/vi/3AkVb6ryll0/hq720.jpg", date:"8 months ago", duration:"3:57", views:"2", isShort:false, tag:"project"},
  {id:"nMcDyaKVOtY", title:"Day #4 Programmer Nganggur", desc:"Hari ke-4 — cerita lapangan.", thumb:"https://i.ytimg.com/vi/nMcDyaKVOtY/hq720.jpg", date:"8 months ago", duration:"1:00:51", views:"15", isShort:false, tag:"series"},
  {id:"eWb7-0uMfac", title:"Day #3 Programmer Nganggur", desc:"Hari ke-3 — tantangan freelance.", thumb:"https://i.ytimg.com/vi/eWb7-0uMfac/hq720.jpg", date:"8 months ago", duration:"56:37", views:"10", isShort:false, tag:"series"},
  {id:"JEzLi1TsqNI", title:"Day #1 Programmer Nganggur", desc:"Hari pertama — awal perjalanan.", thumb:"https://i.ytimg.com/vi/JEzLi1TsqNI/hq720.jpg", date:"8 months ago", duration:"42:31", views:"10", isShort:false, tag:"series"},
  {id:"lpCwC24rNa4", title:"Day #2 Programmer Nganggur", desc:"Hari kedua — adaptasi.", thumb:"https://i.ytimg.com/vi/lpCwC24rNa4/hq720.jpg", date:"8 months ago", duration:"36:55", views:"3", isShort:false, tag:"series"},
  // Shorts (9:16) — tab Shorts
  {id:"D7wVsxPqqtc", title:"GenZ Belajar TypeScript di Zaman AI? #TypeScript #JavaScript #Programming #GenZ #AI #LiveCoding", desc:"Short — GenZ TypeScript live.", thumb:"https://i.ytimg.com/vi/D7wVsxPqqtc/hq720.jpg", date:"recent", duration:"0:29", views:"171", isShort:true, tag:"short"},
  {id:"s2OFRR2ZCPc", title:"EUREKA Milestone", desc:"Short — milestone Eureka.", thumb:"https://i.ytimg.com/vi/s2OFRR2ZCPc/hq720.jpg", date:"recent", duration:"0:16", views:"91", isShort:true, tag:"short"},
  {id:"UtJApwTXZL4", title:"Rahasia Jadi Mobile Developer dan Freelance Sukses di Era AI yang Wajib Kamu Tahu!", desc:"Short — rahasia mobile freelance.", thumb:"https://i.ytimg.com/vi/UtJApwTXZL4/hq720.jpg", date:"recent", duration:"0:59", views:"289", isShort:true, tag:"short"},
  {id:"ttqQh6dmNpY", title:"ngoding kuy", desc:"Short — ngoding kuy.", thumb:"https://i.ytimg.com/vi/ttqQh6dmNpY/hq720.jpg", date:"recent", duration:"0:15", views:"23", isShort:true, tag:"short"},
  {id:"J_2qcRcCG8I", title:"Cooming Soon", desc:"Short — coming soon.", thumb:"https://i.ytimg.com/vi/J_2qcRcCG8I/hq720.jpg", date:"recent", duration:"0:11", views:"744", isShort:true, tag:"short"},
];

export const blogFull: Record<string, {lead:string; sections:{id:string; title:string; body:string}[]}> = {
  "the-play-store-gauntlet": { lead:"The code was done. Then I met the Play Console. If you have only ever shipped to the web, the amount of non-code work to publish a mobile app is a genuine surprise. Here is the checklist I assembled the hard way, four times.", sections:[
    {id:"store-listing-assets", title:"Store listing assets", body:`<ul class="list-disc pl-5 space-y-1.5 text-zinc-300"><li><strong class="text-white">Icon</strong> 512 by 512. <strong class="text-white">Feature graphic</strong> 1024 by 500. At least two phone screenshots.</li><li>The feature graphic is the one people skip. I generated all four with a small Python script (Pillow): a brand-color gradient, the app icon, the title in the app's font, a faint crossword motif. Code is a perfectly good design tool when you need four on-brand banners fast.</li><li>Short description (80 chars) and full description (4000). Write them for the audience, not for a checklist. Mine are casual Bahasa Indonesia, because that is who plays.</li></ul>`},
    {id:"data-safety-honestly", title:"Data safety, honestly", body:`<p>The Data safety form asks what data you collect. The honest answer for these apps: nothing <em>I</em> store, but the SDKs collect things. AdMob takes an advertising ID and coarse location, Sentry takes crash diagnostics, RevenueCat handles purchase data. All of it is "collected and shared", encrypted in transit, not user-deletable in-app. Declare it accurately; Google cross-checks it against your privacy policy.</p>`},
    {id:"the-target-audience-trap", title:"The target-audience trap", body:`<p>This one nearly cost me. In "Target audience and content", I had ticked an age band that included under-13. That silently opted the app into Google's Families policy, which requires a certified child-safe ad SDK and non-personalized ads only. The fix was to set the minimum target age to 13+. Content rating can still be "Everyone / 3+"; those are different fields. If you are not deliberately making a kids app, do not let the target-audience picker turn you into one.</p>`},
    {id:"app-ads-txt", title:"app-ads.txt", body:`<p>Advertisers verify your ad inventory by fetching <code class="mono bg-zinc-800 px-1.5 py-0.5 rounded text-xs">app-ads.txt</code> from the developer website on your store listing. One line:</p><pre class="mt-3 bg-zinc-900 border border-zinc-800 rounded-xl p-4 mono text-xs leading-5 overflow-auto">google.com, pub-XXXXXXXXXX, DIRECT, f08c47fec0942fa0</pre><p class="mt-3">Two gotchas: the website field on each listing must point at the domain that serves the file, and the file must return as plain text with a 200, not get swallowed by your site's 404 handler. Verify with <code class="mono bg-zinc-800 px-1 py-0.5 rounded text-xs">curl</code>, not faith.</p>`},
    {id:"privacy-policy", title:"Privacy policy", body:`<p>Required, and it must be live at the URL you paste, or review rejects you. Mine spells out the SDKs, the advertising ID, and a contact email for data-deletion requests. Since there is no backend, "deletion" is mostly pointing the user at uninstall and the ad-ID reset, which is a legitimate answer for an app that stores nothing server-side.</p>`},
    {id:"the-testing-tracks-and-the-door-i-used", title:"The testing tracks, and the door I used", body:`<p>Internal, closed, open, production. The confusing part: <strong class="text-white">open testing is restricted until you have a production release</strong>, and <strong class="text-white">early access</strong> (the public-beta track for unreleased apps) wanted pre-registration setup. After going in circles, I went straight to production. For a finished, tested app, that was the cleaner door.</p>`},
    {id:"real-time-notifications-and-the-36-hour-wait", title:"Real-time notifications and the 36-hour wait", body:`<p>Several things (RevenueCat product import, service-account validation, app-ads.txt verification) are eventually consistent on Google's side, measured in hours up to a day or two. Set them up early and do not interpret "not working yet" as "broken".</p>`},
    {id:"the-lesson", title:"The lesson", body:`<p>Budget a real chunk of time for the part with no code in it. Make the listing assets early, fill the policy forms honestly, and verify the external checks (app-ads.txt, RTDN, privacy URL) with tools instead of assumptions. The app being done is the halfway point, not the finish line.</p><p class="mt-3 text-zinc-500">Next: what happened once real testers got their hands on it.</p>`},
  ]},
};

